sudo: required
language: generic

services:
  - docker
script:
  - docker run --rm -v $(pwd):/usr/src/app/files -it andmos/markdownlint *.md
  - docker run --rm -v $(pwd):/mnt -it andmos/awesome-bot -f *.csv --allow-redirect --allow 429